site_name: MicroSoft Excel User Documentation
nav:
  - Home: "index.md"
  - Formatting a Table: "formatting-tables.md"
  - Using a Formula: "using-formulas.md"
  - Creating a Chart: "creating-charts.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossary.md"

repo_url: https://github.com/am-eskandari/comp2216-user-guide-project

repo_name: am-eskandari/comp2216-user-guide-project

theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  language: en

    features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # - scheme: default
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    #   primary: teal
    #   accent: purple
    # - scheme: slate
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
    #   primary: teal
    #   accent: lime

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

icon:
  repo: fontawesome/brands/git-alt

extra:
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: https://github.com/am-eskandari
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/am.eskandari
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/am-eskandari/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/am-eskandari"  target="_blank" rel="noopener">Amir Eskandari</a>
  &copy; 2023 <a href="https://github.com/DanielOkonov"  target="_blank" rel="noopener">Daniel Okonov</a>
